services:
  app:
    build: .
    container_name: whatsapp_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: whatsapp_clone
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: whatsapp_db
    restart: always
    environment:
      MYSQL_DATABASE: whatsapp_clone
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro

volumes:
  db_data:
